import { useContext } from "react";
import Head from "next/head";
import { FBContext } from "../context/FBContext";
import Brands from "../components/Brands/Brands";
import Article from "../components/Content/Article";
import LatestShows from "../components/Content/LatestShows";
import LatestShow from "../components/Content/LatestShow";
import { ColorModeContext } from "../context/themeContext";
export default function Home() {
  return (
    <>
      <Head>
        <title>LATEST SHOWS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LatestShow />
        <LatestShows />
      </main>
    </>
  );
}
