import { useContext } from "react";
import Head from "next/head";
import { FBContext } from "../context/FBContext";
import Brands from "../components/Brands/Brands";
import SeasonRes from "../components/Seasons/Seasons";
import Article from "../components/Articles/Article";
import Button from "@mui/material/Button";

export default function Home() {
  const { signIn, logOut, favArticles } = useContext(FBContext);
console.log(favArticles)

  return (
    <div>
      <button onClick={signIn}>sign</button>
      <button onClick={logOut}>signout</button>
      <Button variant="new">Hello World</Button>
      <Head>
        <title>Vogue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SeasonRes />
      <Article />
      <main></main>
    </div>
  );
}
