import Head from "next/head";

import LatestShows from "../components/Content/LatestShows";
import LatestShow from "../components/Content/LatestShow";
import { Divider } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>LATEST SHOWS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LatestShow />
        <Divider sx={{ my: 0.3, color: "text.primary" }} />
        <Divider sx={{ my: 0.3, color: "text.primary" }} />
        <LatestShows />
      </main>
    </>
  );
}
